### ISSUE TITLE
[RedstoneArsenal] Flux-infused pickaxe crashing server

### ISSUE THREAD

**Issue by marcin212** [StarChasers/Testpack#26]
```
java.lang.NoSuchMethodError: redstonearsenal.item.tool.ItemPickaxeRF.harvestBlock(Lnet/minecraft/world/World;IIILnet/minecraft/entity/player/EntityPlayer;)V
	at redstonearsenal.item.tool.ItemPickaxeRF.func_150894_a(ItemPickaxeRF.java:60)
	at net.minecraft.item.ItemStack.func_150999_a(ItemStack.java:309)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:288)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by marcin212** [comment]
https://github.com/CoFH/Feedback/issues/49

**Comment by marcin212** [comment]
fixed
