### ISSUE TITLE
AgriCraft - client disconection

### ISSUE THREAD

**Issue by ka21k** [StarChasers/Testpack#68]
Throw out of server when try to plant a growed seed on crop with Gardening Trowel.

http://hastebin.com/ezoxujojor.avrasm

java.lang.NullPointerException
        at com.InfinityRaider.AgriCraft.api.v1.ItemWithMeta.hashCode(ItemWithMeta.java:43) ~[ItemWithMeta.class:?]
        at java.util.HashMap.hash(HashMap.java:338) ~[?:1.8.0_05]
        at java.util.HashMap.get(HashMap.java:556) ~[?:1.8.0_05]
        at com.InfinityRaider.AgriCraft.farming.GrowthRequirementHandler.getGrowthRequirement(GrowthRequirementHandler.java:121) ~[GrowthRequirementHandler.class:?]
        at com.InfinityRaider.AgriCraft.items.ItemTrowel.onItemUseFirst(ItemTrowel.java:73) ~[ItemTrowel.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.c.p.a(F:19) [fastcraft-1.22-ctest10.jar:?]
        at fastcraft.Hooks.aq(F:153) [fastcraft-1.22-ctest10.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by marcin212** [comment]
fixed
